btagging:
  working_point:
    2016_PreVFP:
      reference:
        btagging_WP: https://btv-wiki.docs.cern.ch/ScaleFactors/UL2016preVFP/
      btagging_algorithm: btagDeepFlavB
      btagging_WP:
        L: 0.0508
        M: 0.2598
        H: 0.6502
    2016_PostVFP:
      reference:
        btagging_WP: https://btv-wiki.docs.cern.ch/ScaleFactors/UL2016postVFP/
      btagging_algorithm: btagDeepFlavB
      btagging_WP:
        L: 0.0480
        M: 0.2489
        H: 0.6377
    '2017':
      reference:
        btagging_WP: https://btv-wiki.docs.cern.ch/ScaleFactors/UL2017/
      btagging_algorithm: btagDeepFlavB
      btagging_WP:
        L: 0.0532
        M: 0.3040
        H: 0.7476
    '2018':
      reference:
        btagging_WP: https://btv-wiki.docs.cern.ch/ScaleFactors/UL2018/
      btagging_algorithm: btagDeepFlavB
      btagging_WP:
        L: 0.0490
        M: 0.2783
        H: 0.7100
    '2022_preEE':
      btagging_algorithm: btagRobustParTAK4B
      btagging_WP:
        L: 0.0849
        M: 0.4319
        T: 0.8482
        XT: 0.9151
        XXT: 0.9874
    '2022_postEE':
      btagging_algorithm: btagRobustParTAK4B
      btagging_WP:
        L: 0.0897
        M: 0.451
        T: 0.8604
        XT: 0.9234
        XXT: 0.9893
    '2023_preBPix':
      btagging_algorithm: btagRobustParTAK4B
      btagging_WP:
        L: 0.0681
        M: 0.3487
        T: 0.7969
        XT: 0.8882
        XXT: 0.9883
    '2023_postBPix':
      btagging_algorithm: btagRobustParTAK4B
      btagging_WP:
        L: 0.0683
        M: 0.3494
        T: 0.7994
        XT: 0.8877
        XXT: 0.9883

jet_scale_factors:
  btagSF:
    '2022_preEE':
      btagEfficiencyFile: 
        btagDeepFlavB: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagDeepFlavB_2022_preEE.json"
        btagPNetB: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagPNetB_2022_preEE.json"
        btagRobustParTAK4B: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagRobustParTAK4B_2022_preEE.json"
      fixed_wp_name_map:
        btagDeepFlavB: "deepJet"
        btagPNetB: "particleNet"
        btagRobustParTAK4B: "robustParticleTransformer"
    '2022_postEE':
      btagEfficiencyFile: 
        btagDeepFlavB: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagDeepFlavB_2022_postEE.json"
        btagPNetB: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagPNetB_2022_postEE.json"
        btagRobustParTAK4B: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagRobustParTAK4B_2022_postEE.json"
      fixed_wp_name_map:
        btagDeepFlavB: "deepJet"
        btagPNetB: "particleNet"
        btagRobustParTAK4B: "robustParticleTransformer"
    '2023_preBPix':
      btagEfficiencyFile: 
        btagDeepFlavB: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagDeepFlavB_2023_preBPix.json"
        btagPNetB: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagPNetB_2023_preBPix.json"
        btagRobustParTAK4B: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagRobustParTAK4B_2023_preBPix.json"
      fixed_wp_name_map:
        btagDeepFlavB: "deepJet"
        btagPNetB: "particleNet"
        btagRobustParTAK4B: "robustParticleTransformer"
    '2023_postBPix':
      btagEfficiencyFile: 
        btagDeepFlavB: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagDeepFlavB_2023_postBPix.json"
        btagPNetB: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagPNetB_2023_postBPix.json"
        btagRobustParTAK4B: "${config_dir:}/btag_efficiencies/btag_efficiencies_btagRobustParTAK4B_2023_postBPix.json"
      fixed_wp_name_map:
        btagDeepFlavB: "deepJet"
        btagPNetB: "particleNet"
        btagRobustParTAK4B: "robustParticleTransformer"
